services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "7997:8080"
    depends_on:
      - db

  core:
    image: event-radar-ai-core:dev
    build:
      context: .
      dockerfile: core/Dockerfile
      target: dev
      args:
        USER_ID: ${USER_ID}
        USER_GID: ${USER_GID}
    ports:
      - "7999:80"
    env_file:
      - .env
    volumes:
      - ./core:/app/core
    depends_on:
      - db
    restart: unless-stopped

  webapp:
    image: event-radar-ai-webapp:dev
    build:
      context: .
      dockerfile: webapp/Dockerfile
      target: dev
      args:
        USER_ID: ${USER_ID}
        USER_GID: ${USER_GID}
    ports:
      - "7998:3000"
    volumes:
      - ./webapp:/app/webapp
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - core
    restart: unless-stopped

volumes:
  pg_data:
